### ISSUE TITLE
set page titles

### ISSUE THREAD

**Issue by aranaur** [SparkMakerspace/MakerSpaceMngSys#9]
see this link: https://laravel.io/forum/04-04-2016-set-the-page-title

**Comment by aranaur** [comment]
in case clarification is needed, I mean html <title> tags in each page's <head>.

**Comment by mmiscool** [comment]
This has been updated. See the base page template.
https://github.com/SparkMakerspace/MakerSpaceMngSys/blob/master/resources/views/scaffold-interface/layouts/app.blade.php
